-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 21:44:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CONDUCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONDUCE` (
  `codemp` INT NOT NULL,
  `matrícula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codemp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `num_emp` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_emp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VEHÍCULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VEHÍCULO` (
  `modelo` VARCHAR(45) NULL,
  `CONDUCE_codemp` INT NOT NULL,
  INDEX `fk_VEHÍCULO_CONDUCE1_idx` (`CONDUCE_codemp` ASC) VISIBLE,
  CONSTRAINT `fk_VEHÍCULO_CONDUCE1`
    FOREIGN KEY (`CONDUCE_codemp`)
    REFERENCES `mydb`.`CONDUCE` (`codemp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EDICIÓN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EDICIÓN` (
  `número` INT NOT NULL,
  `año` YEAR(4) NOT NULL,
  PRIMARY KEY (`número`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LIBRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LIBRO` (
  `ISBN` VARCHAR(24) NOT NULL,
  `título` VARCHAR(45) NOT NULL,
  `subtítulo` VARCHAR(45) NULL,
  `idioma` VARCHAR(45) NULL,
  `editorial` VARCHAR(45) NULL,
  `EDICIÓN_número` INT NOT NULL,
  PRIMARY KEY (`ISBN`, `EDICIÓN_número`),
  INDEX `fk_LIBRO_EDICIÓN1_idx` (`EDICIÓN_número` ASC) VISIBLE,
  CONSTRAINT `fk_LIBRO_EDICIÓN1`
    FOREIGN KEY (`EDICIÓN_número`)
    REFERENCES `mydb`.`EDICIÓN` (`número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AUTOR` (
  `idAUTOR` INT NOT NULL,
  `nombre(s)` VARCHAR(45) NOT NULL,
  `apellido(s)` VARCHAR(45) NOT NULL,
  `LIBRO_ISBN` VARCHAR(24) NOT NULL,
  `LIBRO_EDICIÓN_número` INT NOT NULL,
  PRIMARY KEY (`idAUTOR`, `LIBRO_ISBN`, `LIBRO_EDICIÓN_número`),
  INDEX `fk_AUTOR_LIBRO1_idx` (`LIBRO_ISBN` ASC, `LIBRO_EDICIÓN_número` ASC) VISIBLE,
  CONSTRAINT `fk_AUTOR_LIBRO1`
    FOREIGN KEY (`LIBRO_ISBN` , `LIBRO_EDICIÓN_número`)
    REFERENCES `mydb`.`LIBRO` (`ISBN` , `EDICIÓN_número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `num_emp` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_emp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPARTAMENTO` (
  `num_depto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `presupuesto` DOUBLE NOT NULL,
  `EMPLEADO_num_emp` INT NOT NULL,
  PRIMARY KEY (`num_depto`, `nombre`, `EMPLEADO_num_emp`),
  INDEX `fk_DEPARTAMENTO_EMPLEADO1_idx` (`EMPLEADO_num_emp` ASC) VISIBLE,
  CONSTRAINT `fk_DEPARTAMENTO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_num_emp`)
    REFERENCES `mydb`.`EMPLEADO` (`num_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CITA` (
  `hora` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `codmed` INT NOT NULL,
  `codpac` INT NOT NULL,
  PRIMARY KEY (`hora`, `codpac`, `codmed`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MÉDICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MÉDICO` (
  `nombre` VARCHAR(45) NOT NULL,
  `CITA_hora` INT NOT NULL,
  PRIMARY KEY (`CITA_hora`),
  INDEX `fk_MÉDICO_CITA1_idx` (`CITA_hora` ASC) VISIBLE,
  CONSTRAINT `fk_MÉDICO_CITA1`
    FOREIGN KEY (`CITA_hora`)
    REFERENCES `mydb`.`CITA` (`hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PACIENTE` (
  `nombre` VARCHAR(45) NULL,
  `CITA_hora` INT NOT NULL,
  PRIMARY KEY (`CITA_hora`),
  INDEX `fk_PACIENTE_CITA1_idx` (`CITA_hora` ASC) VISIBLE,
  CONSTRAINT `fk_PACIENTE_CITA1`
    FOREIGN KEY (`CITA_hora`)
    REFERENCES `mydb`.`CITA` (`hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MÉDICO_has_CITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MÉDICO_has_CITA` (
  `MÉDICO_codmed` INT NOT NULL,
  `CITA_hora` INT NOT NULL,
  PRIMARY KEY (`MÉDICO_codmed`, `CITA_hora`),
  INDEX `fk_MÉDICO_has_CITA_CITA1_idx` (`CITA_hora` ASC) VISIBLE,
  CONSTRAINT `fk_MÉDICO_has_CITA_CITA1`
    FOREIGN KEY (`CITA_hora`)
    REFERENCES `mydb`.`CITA` (`hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MÉDICO_has_CITA1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MÉDICO_has_CITA1` (
  `MÉDICO_codmed` INT NOT NULL,
  `CITA_hora` INT NOT NULL,
  PRIMARY KEY (`MÉDICO_codmed`, `CITA_hora`),
  INDEX `fk_MÉDICO_has_CITA1_CITA1_idx` (`CITA_hora` ASC) VISIBLE,
  CONSTRAINT `fk_MÉDICO_has_CITA1_CITA1`
    FOREIGN KEY (`CITA_hora`)
    REFERENCES `mydb`.`CITA` (`hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PÓLIZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PÓLIZA` (
  `número` INT NOT NULL,
  `fecha_ini` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `matrícula` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NULL,
  PRIMARY KEY (`número`, `matrícula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BENEFICIARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BENEFICIARIO` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_naicm` DATE NULL,
  `PÓLIZA_número` INT NOT NULL,
  `PÓLIZA_matrícula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni`),
  INDEX `fk_BENEFICIARIO_PÓLIZA1_idx` (`PÓLIZA_número` ASC, `PÓLIZA_matrícula` ASC) VISIBLE,
  CONSTRAINT `fk_BENEFICIARIO_PÓLIZA1`
    FOREIGN KEY (`PÓLIZA_número` , `PÓLIZA_matrícula`)
    REFERENCES `mydb`.`PÓLIZA` (`número` , `matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
